### ISSUE TITLE
Crear Correo y Cuenta en github

### ISSUE THREAD

**Issue by hsgonzalmu** [profesorlabarca/profesorlabarca.github.io#8]

**Comment by hsgonzalmu** [comment]
CORREO
user: profesorlabarca
pass: weblabarca

**Comment by hsgonzalmu** [comment]
GitHub
user: profesorlabarca
pass: weblabarca1

**Comment by jbkunst** [comment]
Esto es un repositorio publico XD, cualquiera es libre de leer esto XD :cry:

**Comment by profesorlabarca** [comment]
Listo la transferencia, borraré los mensajes de arriba por ser datos sensibles. Eso sí, podrías darselos a Ceci para que los guarde, supongo ella administra cuentas.
